'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="SurveyMaster")>  _
Partial Public Class DataClasses1DataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.Tester.MySettings.Default.SurveyMasterConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property WCFServiceInfos() As System.Data.Linq.Table(Of WCFServiceInfo)
		Get
			Return Me.GetTable(Of WCFServiceInfo)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.WCFServiceInfo")>  _
Partial Public Class WCFServiceInfo
	
	Private _WCFServiceID As Integer
	
	Private _Name As String
	
	Private _ComputerServerName As String
	
	Private _ComputerID As System.Nullable(Of Integer)
	
	Private _WCFSvcTypeID As Integer
	
	Private _IsIncludedExposeEndPt As System.Nullable(Of Boolean)
	
	Private _CommandSvcName As String
	
	Private _BaseAddress As String
	
	Private _Contract As String
	
	Private _Address As String
	
	Private _CommandSvcBaseAddress As String
	
	Private _CommandSvcContract As String
	
	Private _CommandSvcAddress As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WCFServiceID", AutoSync:=AutoSync.Always, DbType:="Int NOT NULL IDENTITY", IsDbGenerated:=true)>  _
	Public Property WCFServiceID() As Integer
		Get
			Return Me._WCFServiceID
		End Get
		Set
			If ((Me._WCFServiceID = value)  _
						= false) Then
				Me._WCFServiceID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Name", DbType:="VarChar(50)")>  _
	Public Property Name() As String
		Get
			Return Me._Name
		End Get
		Set
			If (String.Equals(Me._Name, value) = false) Then
				Me._Name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ComputerServerName", DbType:="VarChar(50)")>  _
	Public Property ComputerServerName() As String
		Get
			Return Me._ComputerServerName
		End Get
		Set
			If (String.Equals(Me._ComputerServerName, value) = false) Then
				Me._ComputerServerName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ComputerID", DbType:="Int")>  _
	Public Property ComputerID() As System.Nullable(Of Integer)
		Get
			Return Me._ComputerID
		End Get
		Set
			If (Me._ComputerID.Equals(value) = false) Then
				Me._ComputerID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WCFSvcTypeID", DbType:="Int NOT NULL")>  _
	Public Property WCFSvcTypeID() As Integer
		Get
			Return Me._WCFSvcTypeID
		End Get
		Set
			If ((Me._WCFSvcTypeID = value)  _
						= false) Then
				Me._WCFSvcTypeID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsIncludedExposeEndPt", DbType:="Bit")>  _
	Public Property IsIncludedExposeEndPt() As System.Nullable(Of Boolean)
		Get
			Return Me._IsIncludedExposeEndPt
		End Get
		Set
			If (Me._IsIncludedExposeEndPt.Equals(value) = false) Then
				Me._IsIncludedExposeEndPt = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CommandSvcName", DbType:="VarChar(50)")>  _
	Public Property CommandSvcName() As String
		Get
			Return Me._CommandSvcName
		End Get
		Set
			If (String.Equals(Me._CommandSvcName, value) = false) Then
				Me._CommandSvcName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BaseAddress", DbType:="VarChar(100)")>  _
	Public Property BaseAddress() As String
		Get
			Return Me._BaseAddress
		End Get
		Set
			If (String.Equals(Me._BaseAddress, value) = false) Then
				Me._BaseAddress = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Contract", DbType:="VarChar(50)")>  _
	Public Property Contract() As String
		Get
			Return Me._Contract
		End Get
		Set
			If (String.Equals(Me._Contract, value) = false) Then
				Me._Contract = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Address", DbType:="VarChar(50)")>  _
	Public Property Address() As String
		Get
			Return Me._Address
		End Get
		Set
			If (String.Equals(Me._Address, value) = false) Then
				Me._Address = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CommandSvcBaseAddress", DbType:="VarChar(100)")>  _
	Public Property CommandSvcBaseAddress() As String
		Get
			Return Me._CommandSvcBaseAddress
		End Get
		Set
			If (String.Equals(Me._CommandSvcBaseAddress, value) = false) Then
				Me._CommandSvcBaseAddress = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CommandSvcContract", DbType:="VarChar(50)")>  _
	Public Property CommandSvcContract() As String
		Get
			Return Me._CommandSvcContract
		End Get
		Set
			If (String.Equals(Me._CommandSvcContract, value) = false) Then
				Me._CommandSvcContract = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CommandSvcAddress", DbType:="VarChar(50)")>  _
	Public Property CommandSvcAddress() As String
		Get
			Return Me._CommandSvcAddress
		End Get
		Set
			If (String.Equals(Me._CommandSvcAddress, value) = false) Then
				Me._CommandSvcAddress = value
			End If
		End Set
	End Property
End Class
