'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="PerceptricsEmail")>  _
Partial Public Class L2S_PerceptricsEmailDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.CmdInfrastructureNS.My.MySettings.Default.PerceptricsEmailConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property EmailAcctInfos() As System.Data.Linq.Table(Of EmailAcctInfo)
		Get
			Return Me.GetTable(Of EmailAcctInfo)
		End Get
	End Property
	
	Public ReadOnly Property EmailForms() As System.Data.Linq.Table(Of EmailForm)
		Get
			Return Me.GetTable(Of EmailForm)
		End Get
	End Property
	
	Public ReadOnly Property EmailFormMessageItems() As System.Data.Linq.Table(Of EmailFormMessageItem)
		Get
			Return Me.GetTable(Of EmailFormMessageItem)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.EmailAcctInfo")>  _
Partial Public Class EmailAcctInfo
	
	Private _ID As Integer
	
	Private _Name As String
	
	Private _EmailAddress As String
	
	Private _Password As String
	
	Private _HostServer As String
	
	Private _Port As System.Nullable(Of Integer)
	
	Private _EnableSSL As System.Nullable(Of Boolean)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.Always, DbType:="Int NOT NULL IDENTITY", IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me._ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Name", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property Name() As String
		Get
			Return Me._Name
		End Get
		Set
			If (String.Equals(Me._Name, value) = false) Then
				Me._Name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmailAddress", DbType:="VarChar(200) NOT NULL", CanBeNull:=false)>  _
	Public Property EmailAddress() As String
		Get
			Return Me._EmailAddress
		End Get
		Set
			If (String.Equals(Me._EmailAddress, value) = false) Then
				Me._EmailAddress = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Password", DbType:="VarChar(50)")>  _
	Public Property Password() As String
		Get
			Return Me._Password
		End Get
		Set
			If (String.Equals(Me._Password, value) = false) Then
				Me._Password = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HostServer", DbType:="VarChar(100)")>  _
	Public Property HostServer() As String
		Get
			Return Me._HostServer
		End Get
		Set
			If (String.Equals(Me._HostServer, value) = false) Then
				Me._HostServer = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Port", DbType:="Int")>  _
	Public Property Port() As System.Nullable(Of Integer)
		Get
			Return Me._Port
		End Get
		Set
			If (Me._Port.Equals(value) = false) Then
				Me._Port = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EnableSSL", DbType:="Bit")>  _
	Public Property EnableSSL() As System.Nullable(Of Boolean)
		Get
			Return Me._EnableSSL
		End Get
		Set
			If (Me._EnableSSL.Equals(value) = false) Then
				Me._EnableSSL = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.EmailForm")>  _
Partial Public Class EmailForm
	
	Private _ID As Integer
	
	Private _FormName As String
	
	Private _DefaultEmailAcctInfoID As System.Nullable(Of Integer)
	
	Private _BlindCopyColxnID As System.Nullable(Of Integer)
	
	Private _FormEnumID As System.Nullable(Of Integer)
	
	Private _HTMLContentSource As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.Always, DbType:="Int NOT NULL IDENTITY", IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me._ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FormName", DbType:="VarChar(50)")>  _
	Public Property FormName() As String
		Get
			Return Me._FormName
		End Get
		Set
			If (String.Equals(Me._FormName, value) = false) Then
				Me._FormName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DefaultEmailAcctInfoID", DbType:="Int")>  _
	Public Property DefaultEmailAcctInfoID() As System.Nullable(Of Integer)
		Get
			Return Me._DefaultEmailAcctInfoID
		End Get
		Set
			If (Me._DefaultEmailAcctInfoID.Equals(value) = false) Then
				Me._DefaultEmailAcctInfoID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BlindCopyColxnID", DbType:="Int")>  _
	Public Property BlindCopyColxnID() As System.Nullable(Of Integer)
		Get
			Return Me._BlindCopyColxnID
		End Get
		Set
			If (Me._BlindCopyColxnID.Equals(value) = false) Then
				Me._BlindCopyColxnID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FormEnumID", DbType:="Int")>  _
	Public Property FormEnumID() As System.Nullable(Of Integer)
		Get
			Return Me._FormEnumID
		End Get
		Set
			If (Me._FormEnumID.Equals(value) = false) Then
				Me._FormEnumID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HTMLContentSource", DbType:="VarChar(150)")>  _
	Public Property HTMLContentSource() As String
		Get
			Return Me._HTMLContentSource
		End Get
		Set
			If (String.Equals(Me._HTMLContentSource, value) = false) Then
				Me._HTMLContentSource = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.EmailFormMessageItem")>  _
Partial Public Class EmailFormMessageItem
	
	Private _ID As Integer
	
	Private _FormID As Integer
	
	Private _KVPKey As String
	
	Private _KVPValue As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.Always, DbType:="Int NOT NULL IDENTITY", IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me._ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FormID", DbType:="Int NOT NULL")>  _
	Public Property FormID() As Integer
		Get
			Return Me._FormID
		End Get
		Set
			If ((Me._FormID = value)  _
						= false) Then
				Me._FormID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KVPKey", DbType:="VarChar(50)")>  _
	Public Property KVPKey() As String
		Get
			Return Me._KVPKey
		End Get
		Set
			If (String.Equals(Me._KVPKey, value) = false) Then
				Me._KVPKey = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KVPValue", DbType:="VarChar(250)")>  _
	Public Property KVPValue() As String
		Get
			Return Me._KVPValue
		End Get
		Set
			If (String.Equals(Me._KVPValue, value) = false) Then
				Me._KVPValue = value
			End If
		End Set
	End Property
End Class
