<?xml version="1.0" encoding="utf-8"?>
<Database Name="Survey4DataStore" Class="L2S_PgItemColxnSDSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.PageContentModel" Member="PageContentModels">
    <Type Name="PageContentModel">
      <Column Name="PageContentModelID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PgItemModelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HostingControlSize" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PageContentElement" Member="PageContentElements">
    <Type Name="PageContentElement">
      <Column Name="PageContentElementID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PageContentModelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PresenterTypeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ViewModel" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuestOptionItemModel" Member="QuestOptionItemModels">
    <Type Name="QuestOptionItemModel">
      <Column Name="QuestOptionItemModelID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PgItemModelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestOptionSetModelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SelectorConfiguration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OptionItemObject" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="QOptionItemText" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OptionIsSelected" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SDSResponseModelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionOptionSetModel" Member="QuestionOptionSetModels">
    <Type Name="QuestionOptionSetModel">
      <Column Name="QuestOptionSetModelID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PgItemModelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PageContentElementID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LayoutConfiguration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UniGridColumns" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UniGridRows" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PgItemModel" Member="PgItemModels">
    <Type Name="PgItemModel">
      <Column Name="PageItemModelID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SurveyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SurveyName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Property1Value" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PageNumber" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="PageOptions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>