'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection
Imports System.Runtime.Serialization


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="SurveyMaster")>  _
Partial Public Class L2S_MasterSurveyDBDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertCustomer(instance As Customer)
    End Sub
  Partial Private Sub UpdateCustomer(instance As Customer)
    End Sub
  Partial Private Sub DeleteCustomer(instance As Customer)
    End Sub
  Partial Private Sub InsertSurveyMaster(instance As SurveyMaster)
    End Sub
  Partial Private Sub UpdateSurveyMaster(instance As SurveyMaster)
    End Sub
  Partial Private Sub DeleteSurveyMaster(instance As SurveyMaster)
    End Sub
  Partial Private Sub InsertSurveyDataStore(instance As SurveyDataStore)
    End Sub
  Partial Private Sub UpdateSurveyDataStore(instance As SurveyDataStore)
    End Sub
  Partial Private Sub DeleteSurveyDataStore(instance As SurveyDataStore)
    End Sub
  Partial Private Sub InsertLoginInfo(instance As LoginInfo)
    End Sub
  Partial Private Sub UpdateLoginInfo(instance As LoginInfo)
    End Sub
  Partial Private Sub DeleteLoginInfo(instance As LoginInfo)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.MasterDBSvcLibr.My.MySettings.Default.SurveyMasterConnectionString1, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property EventItems() As System.Data.Linq.Table(Of EventItem)
		Get
			Return Me.GetTable(Of EventItem)
		End Get
	End Property
	
	Public ReadOnly Property Customers() As System.Data.Linq.Table(Of Customer)
		Get
			Return Me.GetTable(Of Customer)
		End Get
	End Property
	
	Public ReadOnly Property SurveyMasters() As System.Data.Linq.Table(Of SurveyMaster)
		Get
			Return Me.GetTable(Of SurveyMaster)
		End Get
	End Property
	
	Public ReadOnly Property SurveyDataStores() As System.Data.Linq.Table(Of SurveyDataStore)
		Get
			Return Me.GetTable(Of SurveyDataStore)
		End Get
	End Property
	
	Public ReadOnly Property LoginInfos() As System.Data.Linq.Table(Of LoginInfo)
		Get
			Return Me.GetTable(Of LoginInfo)
		End Get
	End Property
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.proc_GetGlobalMasterLoginDataByLoginName")>  _
	Public Function proc_GetGlobalMasterLoginDataByLoginName(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="LoginEMail", DbType:="VarChar(100)")> ByVal loginEMail As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="PasswordHash", DbType:="Int")> ByVal passwordHash As System.Nullable(Of Integer)) As ISingleResult(Of proc_GetGlobalMasterLoginDataByLoginNameResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), loginEMail, passwordHash)
		Return CType(result.ReturnValue,ISingleResult(Of proc_GetGlobalMasterLoginDataByLoginNameResult))
	End Function
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Event"),  _
 Global.System.Runtime.Serialization.DataContractAttribute()>  _
Partial Public Class EventItem
	
	Private _EventItemID As Integer
	
	Private _EventInfoID As Integer
	
	Private _EventOccurredDate As Date
	
	Private _EventData As String
	
	Private _SurveyID As System.Nullable(Of Integer)
	
	Private _LoginID As System.Nullable(Of Integer)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EventItemID", AutoSync:=AutoSync.Always, DbType:="Int NOT NULL IDENTITY", IsDbGenerated:=true),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
	Public Property EventItemID() As Integer
		Get
			Return Me._EventItemID
		End Get
		Set
			If ((Me._EventItemID = value)  _
						= false) Then
				Me._EventItemID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EventInfoID", DbType:="Int NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
	Public Property EventInfoID() As Integer
		Get
			Return Me._EventInfoID
		End Get
		Set
			If ((Me._EventInfoID = value)  _
						= false) Then
				Me._EventInfoID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EventOccurredDate", DbType:="DateTime NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
	Public Property EventOccurredDate() As Date
		Get
			Return Me._EventOccurredDate
		End Get
		Set
			If ((Me._EventOccurredDate = value)  _
						= false) Then
				Me._EventOccurredDate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EventData", DbType:="VarChar(100)"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
	Public Property EventData() As String
		Get
			Return Me._EventData
		End Get
		Set
			If (String.Equals(Me._EventData, value) = false) Then
				Me._EventData = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SurveyID", DbType:="Int"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
	Public Property SurveyID() As System.Nullable(Of Integer)
		Get
			Return Me._SurveyID
		End Get
		Set
			If (Me._SurveyID.Equals(value) = false) Then
				Me._SurveyID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LoginID", DbType:="Int"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
	Public Property LoginID() As System.Nullable(Of Integer)
		Get
			Return Me._LoginID
		End Get
		Set
			If (Me._LoginID.Equals(value) = false) Then
				Me._LoginID = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Customer"),  _
 Global.System.Runtime.Serialization.DataContractAttribute()>  _
Partial Public Class Customer
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _CustomerID As Integer
	
	Private _CustomerName As String
	
	Private _PrimaryServerID As Integer
	
	Private _CurrentAuthorizationID As Integer
	
	Private _PrimaryContactInfoID As Integer
	
	Private _CustomerSurveyMasterID As Integer
	
	Private _PrimaryDataStoreID As Integer
	
	Private _RDENTQueueURI_ID As Integer
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnCustomerIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnCustomerIDChanged()
    End Sub
    Partial Private Sub OnCustomerNameChanging(value As String)
    End Sub
    Partial Private Sub OnCustomerNameChanged()
    End Sub
    Partial Private Sub OnPrimaryServerIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnPrimaryServerIDChanged()
    End Sub
    Partial Private Sub OnCurrentAuthorizationIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnCurrentAuthorizationIDChanged()
    End Sub
    Partial Private Sub OnPrimaryContactInfoIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnPrimaryContactInfoIDChanged()
    End Sub
    Partial Private Sub OnCustomerSurveyMasterIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnCustomerSurveyMasterIDChanged()
    End Sub
    Partial Private Sub OnPrimaryDataStoreIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnPrimaryDataStoreIDChanged()
    End Sub
    Partial Private Sub OnRDENTQueueURI_IDChanging(value As Integer)
    End Sub
    Partial Private Sub OnRDENTQueueURI_IDChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me.Initialize
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomerID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
	Public Property CustomerID() As Integer
		Get
			Return Me._CustomerID
		End Get
		Set
			If ((Me._CustomerID = value)  _
						= false) Then
				Me.OnCustomerIDChanging(value)
				Me.SendPropertyChanging
				Me._CustomerID = value
				Me.SendPropertyChanged("CustomerID")
				Me.OnCustomerIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomerName", DbType:="VarChar(75) NOT NULL", CanBeNull:=false),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
	Public Property CustomerName() As String
		Get
			Return Me._CustomerName
		End Get
		Set
			If (String.Equals(Me._CustomerName, value) = false) Then
				Me.OnCustomerNameChanging(value)
				Me.SendPropertyChanging
				Me._CustomerName = value
				Me.SendPropertyChanged("CustomerName")
				Me.OnCustomerNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PrimaryServerID", DbType:="Int NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
	Public Property PrimaryServerID() As Integer
		Get
			Return Me._PrimaryServerID
		End Get
		Set
			If ((Me._PrimaryServerID = value)  _
						= false) Then
				Me.OnPrimaryServerIDChanging(value)
				Me.SendPropertyChanging
				Me._PrimaryServerID = value
				Me.SendPropertyChanged("PrimaryServerID")
				Me.OnPrimaryServerIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CurrentAuthorizationID", DbType:="Int NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
	Public Property CurrentAuthorizationID() As Integer
		Get
			Return Me._CurrentAuthorizationID
		End Get
		Set
			If ((Me._CurrentAuthorizationID = value)  _
						= false) Then
				Me.OnCurrentAuthorizationIDChanging(value)
				Me.SendPropertyChanging
				Me._CurrentAuthorizationID = value
				Me.SendPropertyChanged("CurrentAuthorizationID")
				Me.OnCurrentAuthorizationIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PrimaryContactInfoID", DbType:="Int NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
	Public Property PrimaryContactInfoID() As Integer
		Get
			Return Me._PrimaryContactInfoID
		End Get
		Set
			If ((Me._PrimaryContactInfoID = value)  _
						= false) Then
				Me.OnPrimaryContactInfoIDChanging(value)
				Me.SendPropertyChanging
				Me._PrimaryContactInfoID = value
				Me.SendPropertyChanged("PrimaryContactInfoID")
				Me.OnPrimaryContactInfoIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomerSurveyMasterID", DbType:="Int NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
	Public Property CustomerSurveyMasterID() As Integer
		Get
			Return Me._CustomerSurveyMasterID
		End Get
		Set
			If ((Me._CustomerSurveyMasterID = value)  _
						= false) Then
				Me.OnCustomerSurveyMasterIDChanging(value)
				Me.SendPropertyChanging
				Me._CustomerSurveyMasterID = value
				Me.SendPropertyChanged("CustomerSurveyMasterID")
				Me.OnCustomerSurveyMasterIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PrimaryDataStoreID", DbType:="Int NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=7)>  _
	Public Property PrimaryDataStoreID() As Integer
		Get
			Return Me._PrimaryDataStoreID
		End Get
		Set
			If ((Me._PrimaryDataStoreID = value)  _
						= false) Then
				Me.OnPrimaryDataStoreIDChanging(value)
				Me.SendPropertyChanging
				Me._PrimaryDataStoreID = value
				Me.SendPropertyChanged("PrimaryDataStoreID")
				Me.OnPrimaryDataStoreIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RDENTQueueURI_ID", DbType:="Int NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=8)>  _
	Public Property RDENTQueueURI_ID() As Integer
		Get
			Return Me._RDENTQueueURI_ID
		End Get
		Set
			If ((Me._RDENTQueueURI_ID = value)  _
						= false) Then
				Me.OnRDENTQueueURI_IDChanging(value)
				Me.SendPropertyChanging
				Me._RDENTQueueURI_ID = value
				Me.SendPropertyChanged("RDENTQueueURI_ID")
				Me.OnRDENTQueueURI_IDChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub Initialize()
		OnCreated
	End Sub
	
	<Global.System.Runtime.Serialization.OnDeserializingAttribute(),  _
	 Global.System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)>  _
	Public Sub OnDeserializing(ByVal context As StreamingContext)
		Me.Initialize
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SurveyMaster"),  _
 Global.System.Runtime.Serialization.DataContractAttribute()>  _
Partial Public Class SurveyMaster
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _SurveyID As Integer
	
	Private _SurveyDescription As String
	
	Private _QueueURI As String
	
	Private _QueueName As String
	
	Private _QueueComputer As String
	
	Private _SurveyDataStoreID As Integer
	
	Private _SurveyDataStoreComputer As String
	
	Private _LoginID As Integer
	
	Private _CreatedDate As System.Nullable(Of Date)
	
	Private _LastModifiedDate As System.Nullable(Of Date)
	
	Private _FirstRespondentPostedDate As System.Nullable(Of Date)
	
	Private _LastRespondentPostedDate As System.Nullable(Of Date)
	
	Private _RespondenStartedtCount As Integer
	
	Private _RespondentCompletedCount As Integer
	
	Private _LastRespondentStartedDate As System.Nullable(Of Date)
	
	Private _LastRespondentCompletedDate As System.Nullable(Of Date)
	
	Private _ActiveRespondentsCount As Integer
	
	Private _FirstPublishedDate As System.Nullable(Of Date)
	
	Private _LastPublishedDate As System.Nullable(Of Date)
	
	Private _SurveyType As Integer
	
	Private _ResponsePostingSvcIsActive As Boolean
	
	Private _StatisticsViewerSvcIsActive As Boolean
	
	Private _FirstStatisticsViewerDate As System.Nullable(Of Date)
	
	Private _LastStatisticsViewerDate As System.Nullable(Of Date)
	
	Private _SurveyStateID As Integer
	
	Private _Model As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnSurveyIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnSurveyIDChanged()
    End Sub
    Partial Private Sub OnSurveyDescriptionChanging(value As String)
    End Sub
    Partial Private Sub OnSurveyDescriptionChanged()
    End Sub
    Partial Private Sub OnQueueURIChanging(value As String)
    End Sub
    Partial Private Sub OnQueueURIChanged()
    End Sub
    Partial Private Sub OnQueueNameChanging(value As String)
    End Sub
    Partial Private Sub OnQueueNameChanged()
    End Sub
    Partial Private Sub OnQueueComputerChanging(value As String)
    End Sub
    Partial Private Sub OnQueueComputerChanged()
    End Sub
    Partial Private Sub OnSurveyDataStoreIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnSurveyDataStoreIDChanged()
    End Sub
    Partial Private Sub OnSurveyDataStoreComputerChanging(value As String)
    End Sub
    Partial Private Sub OnSurveyDataStoreComputerChanged()
    End Sub
    Partial Private Sub OnLoginIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnLoginIDChanged()
    End Sub
    Partial Private Sub OnCreatedDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCreatedDateChanged()
    End Sub
    Partial Private Sub OnLastModifiedDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnLastModifiedDateChanged()
    End Sub
    Partial Private Sub OnFirstRespondentPostedDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFirstRespondentPostedDateChanged()
    End Sub
    Partial Private Sub OnLastRespondentPostedDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnLastRespondentPostedDateChanged()
    End Sub
    Partial Private Sub OnRespondenStartedtCountChanging(value As Integer)
    End Sub
    Partial Private Sub OnRespondenStartedtCountChanged()
    End Sub
    Partial Private Sub OnRespondentCompletedCountChanging(value As Integer)
    End Sub
    Partial Private Sub OnRespondentCompletedCountChanged()
    End Sub
    Partial Private Sub OnLastRespondentStartedDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnLastRespondentStartedDateChanged()
    End Sub
    Partial Private Sub OnLastRespondentCompletedDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnLastRespondentCompletedDateChanged()
    End Sub
    Partial Private Sub OnActiveRespondentsCountChanging(value As Integer)
    End Sub
    Partial Private Sub OnActiveRespondentsCountChanged()
    End Sub
    Partial Private Sub OnFirstPublishedDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFirstPublishedDateChanged()
    End Sub
    Partial Private Sub OnLastPublishedDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnLastPublishedDateChanged()
    End Sub
    Partial Private Sub OnSurveyTypeChanging(value As Integer)
    End Sub
    Partial Private Sub OnSurveyTypeChanged()
    End Sub
    Partial Private Sub OnResponsePostingSvcIsActiveChanging(value As Boolean)
    End Sub
    Partial Private Sub OnResponsePostingSvcIsActiveChanged()
    End Sub
    Partial Private Sub OnStatisticsViewerSvcIsActiveChanging(value As Boolean)
    End Sub
    Partial Private Sub OnStatisticsViewerSvcIsActiveChanged()
    End Sub
    Partial Private Sub OnFirstStatisticsViewerDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFirstStatisticsViewerDateChanged()
    End Sub
    Partial Private Sub OnLastStatisticsViewerDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnLastStatisticsViewerDateChanged()
    End Sub
    Partial Private Sub OnSurveyStateIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnSurveyStateIDChanged()
    End Sub
    Partial Private Sub OnModelChanging(value As String)
    End Sub
    Partial Private Sub OnModelChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me.Initialize
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SurveyID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
	Public Property SurveyID() As Integer
		Get
			Return Me._SurveyID
		End Get
		Set
			If ((Me._SurveyID = value)  _
						= false) Then
				Me.OnSurveyIDChanging(value)
				Me.SendPropertyChanging
				Me._SurveyID = value
				Me.SendPropertyChanged("SurveyID")
				Me.OnSurveyIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SurveyDescription", DbType:="VarChar(50) NOT NULL", CanBeNull:=false),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
	Public Property SurveyDescription() As String
		Get
			Return Me._SurveyDescription
		End Get
		Set
			If (String.Equals(Me._SurveyDescription, value) = false) Then
				Me.OnSurveyDescriptionChanging(value)
				Me.SendPropertyChanging
				Me._SurveyDescription = value
				Me.SendPropertyChanged("SurveyDescription")
				Me.OnSurveyDescriptionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_QueueURI", DbType:="VarChar(50) NOT NULL", CanBeNull:=false),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
	Public Property QueueURI() As String
		Get
			Return Me._QueueURI
		End Get
		Set
			If (String.Equals(Me._QueueURI, value) = false) Then
				Me.OnQueueURIChanging(value)
				Me.SendPropertyChanging
				Me._QueueURI = value
				Me.SendPropertyChanged("QueueURI")
				Me.OnQueueURIChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_QueueName", DbType:="VarChar(50) NOT NULL", CanBeNull:=false),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
	Public Property QueueName() As String
		Get
			Return Me._QueueName
		End Get
		Set
			If (String.Equals(Me._QueueName, value) = false) Then
				Me.OnQueueNameChanging(value)
				Me.SendPropertyChanging
				Me._QueueName = value
				Me.SendPropertyChanged("QueueName")
				Me.OnQueueNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_QueueComputer", DbType:="VarChar(50) NOT NULL", CanBeNull:=false),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
	Public Property QueueComputer() As String
		Get
			Return Me._QueueComputer
		End Get
		Set
			If (String.Equals(Me._QueueComputer, value) = false) Then
				Me.OnQueueComputerChanging(value)
				Me.SendPropertyChanging
				Me._QueueComputer = value
				Me.SendPropertyChanged("QueueComputer")
				Me.OnQueueComputerChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SurveyDataStoreID", DbType:="Int NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
	Public Property SurveyDataStoreID() As Integer
		Get
			Return Me._SurveyDataStoreID
		End Get
		Set
			If ((Me._SurveyDataStoreID = value)  _
						= false) Then
				Me.OnSurveyDataStoreIDChanging(value)
				Me.SendPropertyChanging
				Me._SurveyDataStoreID = value
				Me.SendPropertyChanged("SurveyDataStoreID")
				Me.OnSurveyDataStoreIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SurveyDataStoreComputer", DbType:="VarChar(50) NOT NULL", CanBeNull:=false),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=7)>  _
	Public Property SurveyDataStoreComputer() As String
		Get
			Return Me._SurveyDataStoreComputer
		End Get
		Set
			If (String.Equals(Me._SurveyDataStoreComputer, value) = false) Then
				Me.OnSurveyDataStoreComputerChanging(value)
				Me.SendPropertyChanging
				Me._SurveyDataStoreComputer = value
				Me.SendPropertyChanged("SurveyDataStoreComputer")
				Me.OnSurveyDataStoreComputerChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LoginID", DbType:="Int NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=8)>  _
	Public Property LoginID() As Integer
		Get
			Return Me._LoginID
		End Get
		Set
			If ((Me._LoginID = value)  _
						= false) Then
				Me.OnLoginIDChanging(value)
				Me.SendPropertyChanging
				Me._LoginID = value
				Me.SendPropertyChanged("LoginID")
				Me.OnLoginIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreatedDate", DbType:="DateTime"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=9)>  _
	Public Property CreatedDate() As System.Nullable(Of Date)
		Get
			Return Me._CreatedDate
		End Get
		Set
			If (Me._CreatedDate.Equals(value) = false) Then
				Me.OnCreatedDateChanging(value)
				Me.SendPropertyChanging
				Me._CreatedDate = value
				Me.SendPropertyChanged("CreatedDate")
				Me.OnCreatedDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastModifiedDate", DbType:="DateTime"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=10)>  _
	Public Property LastModifiedDate() As System.Nullable(Of Date)
		Get
			Return Me._LastModifiedDate
		End Get
		Set
			If (Me._LastModifiedDate.Equals(value) = false) Then
				Me.OnLastModifiedDateChanging(value)
				Me.SendPropertyChanging
				Me._LastModifiedDate = value
				Me.SendPropertyChanged("LastModifiedDate")
				Me.OnLastModifiedDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FirstRespondentPostedDate", DbType:="DateTime"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=11)>  _
	Public Property FirstRespondentPostedDate() As System.Nullable(Of Date)
		Get
			Return Me._FirstRespondentPostedDate
		End Get
		Set
			If (Me._FirstRespondentPostedDate.Equals(value) = false) Then
				Me.OnFirstRespondentPostedDateChanging(value)
				Me.SendPropertyChanging
				Me._FirstRespondentPostedDate = value
				Me.SendPropertyChanged("FirstRespondentPostedDate")
				Me.OnFirstRespondentPostedDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastRespondentPostedDate", DbType:="DateTime"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=12)>  _
	Public Property LastRespondentPostedDate() As System.Nullable(Of Date)
		Get
			Return Me._LastRespondentPostedDate
		End Get
		Set
			If (Me._LastRespondentPostedDate.Equals(value) = false) Then
				Me.OnLastRespondentPostedDateChanging(value)
				Me.SendPropertyChanging
				Me._LastRespondentPostedDate = value
				Me.SendPropertyChanged("LastRespondentPostedDate")
				Me.OnLastRespondentPostedDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RespondenStartedtCount", DbType:="Int NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=13)>  _
	Public Property RespondenStartedtCount() As Integer
		Get
			Return Me._RespondenStartedtCount
		End Get
		Set
			If ((Me._RespondenStartedtCount = value)  _
						= false) Then
				Me.OnRespondenStartedtCountChanging(value)
				Me.SendPropertyChanging
				Me._RespondenStartedtCount = value
				Me.SendPropertyChanged("RespondenStartedtCount")
				Me.OnRespondenStartedtCountChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RespondentCompletedCount", DbType:="Int NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=14)>  _
	Public Property RespondentCompletedCount() As Integer
		Get
			Return Me._RespondentCompletedCount
		End Get
		Set
			If ((Me._RespondentCompletedCount = value)  _
						= false) Then
				Me.OnRespondentCompletedCountChanging(value)
				Me.SendPropertyChanging
				Me._RespondentCompletedCount = value
				Me.SendPropertyChanged("RespondentCompletedCount")
				Me.OnRespondentCompletedCountChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastRespondentStartedDate", DbType:="DateTime"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=15)>  _
	Public Property LastRespondentStartedDate() As System.Nullable(Of Date)
		Get
			Return Me._LastRespondentStartedDate
		End Get
		Set
			If (Me._LastRespondentStartedDate.Equals(value) = false) Then
				Me.OnLastRespondentStartedDateChanging(value)
				Me.SendPropertyChanging
				Me._LastRespondentStartedDate = value
				Me.SendPropertyChanged("LastRespondentStartedDate")
				Me.OnLastRespondentStartedDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastRespondentCompletedDate", DbType:="DateTime"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=16)>  _
	Public Property LastRespondentCompletedDate() As System.Nullable(Of Date)
		Get
			Return Me._LastRespondentCompletedDate
		End Get
		Set
			If (Me._LastRespondentCompletedDate.Equals(value) = false) Then
				Me.OnLastRespondentCompletedDateChanging(value)
				Me.SendPropertyChanging
				Me._LastRespondentCompletedDate = value
				Me.SendPropertyChanged("LastRespondentCompletedDate")
				Me.OnLastRespondentCompletedDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ActiveRespondentsCount", DbType:="Int NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=17)>  _
	Public Property ActiveRespondentsCount() As Integer
		Get
			Return Me._ActiveRespondentsCount
		End Get
		Set
			If ((Me._ActiveRespondentsCount = value)  _
						= false) Then
				Me.OnActiveRespondentsCountChanging(value)
				Me.SendPropertyChanging
				Me._ActiveRespondentsCount = value
				Me.SendPropertyChanged("ActiveRespondentsCount")
				Me.OnActiveRespondentsCountChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FirstPublishedDate", DbType:="DateTime"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=18)>  _
	Public Property FirstPublishedDate() As System.Nullable(Of Date)
		Get
			Return Me._FirstPublishedDate
		End Get
		Set
			If (Me._FirstPublishedDate.Equals(value) = false) Then
				Me.OnFirstPublishedDateChanging(value)
				Me.SendPropertyChanging
				Me._FirstPublishedDate = value
				Me.SendPropertyChanged("FirstPublishedDate")
				Me.OnFirstPublishedDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastPublishedDate", DbType:="DateTime"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=19)>  _
	Public Property LastPublishedDate() As System.Nullable(Of Date)
		Get
			Return Me._LastPublishedDate
		End Get
		Set
			If (Me._LastPublishedDate.Equals(value) = false) Then
				Me.OnLastPublishedDateChanging(value)
				Me.SendPropertyChanging
				Me._LastPublishedDate = value
				Me.SendPropertyChanged("LastPublishedDate")
				Me.OnLastPublishedDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SurveyType", DbType:="Int NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=20)>  _
	Public Property SurveyType() As Integer
		Get
			Return Me._SurveyType
		End Get
		Set
			If ((Me._SurveyType = value)  _
						= false) Then
				Me.OnSurveyTypeChanging(value)
				Me.SendPropertyChanging
				Me._SurveyType = value
				Me.SendPropertyChanged("SurveyType")
				Me.OnSurveyTypeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ResponsePostingSvcIsActive", DbType:="Bit NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=21)>  _
	Public Property ResponsePostingSvcIsActive() As Boolean
		Get
			Return Me._ResponsePostingSvcIsActive
		End Get
		Set
			If ((Me._ResponsePostingSvcIsActive = value)  _
						= false) Then
				Me.OnResponsePostingSvcIsActiveChanging(value)
				Me.SendPropertyChanging
				Me._ResponsePostingSvcIsActive = value
				Me.SendPropertyChanged("ResponsePostingSvcIsActive")
				Me.OnResponsePostingSvcIsActiveChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StatisticsViewerSvcIsActive", DbType:="Bit NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=22)>  _
	Public Property StatisticsViewerSvcIsActive() As Boolean
		Get
			Return Me._StatisticsViewerSvcIsActive
		End Get
		Set
			If ((Me._StatisticsViewerSvcIsActive = value)  _
						= false) Then
				Me.OnStatisticsViewerSvcIsActiveChanging(value)
				Me.SendPropertyChanging
				Me._StatisticsViewerSvcIsActive = value
				Me.SendPropertyChanged("StatisticsViewerSvcIsActive")
				Me.OnStatisticsViewerSvcIsActiveChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FirstStatisticsViewerDate", DbType:="DateTime"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=23)>  _
	Public Property FirstStatisticsViewerDate() As System.Nullable(Of Date)
		Get
			Return Me._FirstStatisticsViewerDate
		End Get
		Set
			If (Me._FirstStatisticsViewerDate.Equals(value) = false) Then
				Me.OnFirstStatisticsViewerDateChanging(value)
				Me.SendPropertyChanging
				Me._FirstStatisticsViewerDate = value
				Me.SendPropertyChanged("FirstStatisticsViewerDate")
				Me.OnFirstStatisticsViewerDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastStatisticsViewerDate", DbType:="DateTime"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=24)>  _
	Public Property LastStatisticsViewerDate() As System.Nullable(Of Date)
		Get
			Return Me._LastStatisticsViewerDate
		End Get
		Set
			If (Me._LastStatisticsViewerDate.Equals(value) = false) Then
				Me.OnLastStatisticsViewerDateChanging(value)
				Me.SendPropertyChanging
				Me._LastStatisticsViewerDate = value
				Me.SendPropertyChanged("LastStatisticsViewerDate")
				Me.OnLastStatisticsViewerDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SurveyStateID", DbType:="Int NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=25)>  _
	Public Property SurveyStateID() As Integer
		Get
			Return Me._SurveyStateID
		End Get
		Set
			If ((Me._SurveyStateID = value)  _
						= false) Then
				Me.OnSurveyStateIDChanging(value)
				Me.SendPropertyChanging
				Me._SurveyStateID = value
				Me.SendPropertyChanged("SurveyStateID")
				Me.OnSurveyStateIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Model", DbType:="VarChar(MAX)"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=26)>  _
	Public Property Model() As String
		Get
			Return Me._Model
		End Get
		Set
			If (String.Equals(Me._Model, value) = false) Then
				Me.OnModelChanging(value)
				Me.SendPropertyChanging
				Me._Model = value
				Me.SendPropertyChanged("Model")
				Me.OnModelChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub Initialize()
		OnCreated
	End Sub
	
	<Global.System.Runtime.Serialization.OnDeserializingAttribute(),  _
	 Global.System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)>  _
	Public Sub OnDeserializing(ByVal context As StreamingContext)
		Me.Initialize
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SurveyDataStore"),  _
 Global.System.Runtime.Serialization.DataContractAttribute()>  _
Partial Public Class SurveyDataStore
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _SurveyDataStoreID As Integer
	
	Private _AbsolutePath As String
	
	Private _ComputerID As Integer
	
	Private _DatabaseName As String
	
	Private _CnxnString As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnSurveyDataStoreIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnSurveyDataStoreIDChanged()
    End Sub
    Partial Private Sub OnAbsolutePathChanging(value As String)
    End Sub
    Partial Private Sub OnAbsolutePathChanged()
    End Sub
    Partial Private Sub OnComputerIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnComputerIDChanged()
    End Sub
    Partial Private Sub OnDatabaseNameChanging(value As String)
    End Sub
    Partial Private Sub OnDatabaseNameChanged()
    End Sub
    Partial Private Sub OnCnxnStringChanging(value As String)
    End Sub
    Partial Private Sub OnCnxnStringChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me.Initialize
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SurveyDataStoreID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
	Public Property SurveyDataStoreID() As Integer
		Get
			Return Me._SurveyDataStoreID
		End Get
		Set
			If ((Me._SurveyDataStoreID = value)  _
						= false) Then
				Me.OnSurveyDataStoreIDChanging(value)
				Me.SendPropertyChanging
				Me._SurveyDataStoreID = value
				Me.SendPropertyChanged("SurveyDataStoreID")
				Me.OnSurveyDataStoreIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AbsolutePath", DbType:="VarChar(350) NOT NULL", CanBeNull:=false),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
	Public Property AbsolutePath() As String
		Get
			Return Me._AbsolutePath
		End Get
		Set
			If (String.Equals(Me._AbsolutePath, value) = false) Then
				Me.OnAbsolutePathChanging(value)
				Me.SendPropertyChanging
				Me._AbsolutePath = value
				Me.SendPropertyChanged("AbsolutePath")
				Me.OnAbsolutePathChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ComputerID", DbType:="Int NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
	Public Property ComputerID() As Integer
		Get
			Return Me._ComputerID
		End Get
		Set
			If ((Me._ComputerID = value)  _
						= false) Then
				Me.OnComputerIDChanging(value)
				Me.SendPropertyChanging
				Me._ComputerID = value
				Me.SendPropertyChanged("ComputerID")
				Me.OnComputerIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DatabaseName", DbType:="VarChar(250)"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
	Public Property DatabaseName() As String
		Get
			Return Me._DatabaseName
		End Get
		Set
			If (String.Equals(Me._DatabaseName, value) = false) Then
				Me.OnDatabaseNameChanging(value)
				Me.SendPropertyChanging
				Me._DatabaseName = value
				Me.SendPropertyChanged("DatabaseName")
				Me.OnDatabaseNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CnxnString", DbType:="VarChar(350)"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
	Public Property CnxnString() As String
		Get
			Return Me._CnxnString
		End Get
		Set
			If (String.Equals(Me._CnxnString, value) = false) Then
				Me.OnCnxnStringChanging(value)
				Me.SendPropertyChanging
				Me._CnxnString = value
				Me.SendPropertyChanged("CnxnString")
				Me.OnCnxnStringChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub Initialize()
		OnCreated
	End Sub
	
	<Global.System.Runtime.Serialization.OnDeserializingAttribute(),  _
	 Global.System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)>  _
	Public Sub OnDeserializing(ByVal context As StreamingContext)
		Me.Initialize
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.LoginInfo"),  _
 Global.System.Runtime.Serialization.DataContractAttribute()>  _
Partial Public Class LoginInfo
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _LogInID As Integer
	
	Private _LoginEmail As String
	
	Private _CustomerID As Integer
	
	Private _LastLoginDate As Date
	
	Private _IsLoggedIn As Boolean
	
	Private _PasswordHash As Integer
	
	Private _PasswordLastSetDate As System.Nullable(Of Date)
	
	Private _LastSaltByteArray As System.Data.Linq.Binary
	
	Private _LastSaltMechanismID As System.Nullable(Of Integer)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnLogInIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnLogInIDChanged()
    End Sub
    Partial Private Sub OnLoginEmailChanging(value As String)
    End Sub
    Partial Private Sub OnLoginEmailChanged()
    End Sub
    Partial Private Sub OnCustomerIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnCustomerIDChanged()
    End Sub
    Partial Private Sub OnLastLoginDateChanging(value As Date)
    End Sub
    Partial Private Sub OnLastLoginDateChanged()
    End Sub
    Partial Private Sub OnIsLoggedInChanging(value As Boolean)
    End Sub
    Partial Private Sub OnIsLoggedInChanged()
    End Sub
    Partial Private Sub OnPasswordHashChanging(value As Integer)
    End Sub
    Partial Private Sub OnPasswordHashChanged()
    End Sub
    Partial Private Sub OnPasswordLastSetDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnPasswordLastSetDateChanged()
    End Sub
    Partial Private Sub OnLastSaltByteArrayChanging(value As System.Data.Linq.Binary)
    End Sub
    Partial Private Sub OnLastSaltByteArrayChanged()
    End Sub
    Partial Private Sub OnLastSaltMechanismIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnLastSaltMechanismIDChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me.Initialize
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LogInID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
	Public Property LogInID() As Integer
		Get
			Return Me._LogInID
		End Get
		Set
			If ((Me._LogInID = value)  _
						= false) Then
				Me.OnLogInIDChanging(value)
				Me.SendPropertyChanging
				Me._LogInID = value
				Me.SendPropertyChanged("LogInID")
				Me.OnLogInIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LoginEmail", DbType:="VarChar(100) NOT NULL", CanBeNull:=false),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
	Public Property LoginEmail() As String
		Get
			Return Me._LoginEmail
		End Get
		Set
			If (String.Equals(Me._LoginEmail, value) = false) Then
				Me.OnLoginEmailChanging(value)
				Me.SendPropertyChanging
				Me._LoginEmail = value
				Me.SendPropertyChanged("LoginEmail")
				Me.OnLoginEmailChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomerID", DbType:="Int NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
	Public Property CustomerID() As Integer
		Get
			Return Me._CustomerID
		End Get
		Set
			If ((Me._CustomerID = value)  _
						= false) Then
				Me.OnCustomerIDChanging(value)
				Me.SendPropertyChanging
				Me._CustomerID = value
				Me.SendPropertyChanged("CustomerID")
				Me.OnCustomerIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastLoginDate", DbType:="DateTime NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
	Public Property LastLoginDate() As Date
		Get
			Return Me._LastLoginDate
		End Get
		Set
			If ((Me._LastLoginDate = value)  _
						= false) Then
				Me.OnLastLoginDateChanging(value)
				Me.SendPropertyChanging
				Me._LastLoginDate = value
				Me.SendPropertyChanged("LastLoginDate")
				Me.OnLastLoginDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsLoggedIn", DbType:="Bit NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
	Public Property IsLoggedIn() As Boolean
		Get
			Return Me._IsLoggedIn
		End Get
		Set
			If ((Me._IsLoggedIn = value)  _
						= false) Then
				Me.OnIsLoggedInChanging(value)
				Me.SendPropertyChanging
				Me._IsLoggedIn = value
				Me.SendPropertyChanged("IsLoggedIn")
				Me.OnIsLoggedInChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PasswordHash", DbType:="Int NOT NULL"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
	Public Property PasswordHash() As Integer
		Get
			Return Me._PasswordHash
		End Get
		Set
			If ((Me._PasswordHash = value)  _
						= false) Then
				Me.OnPasswordHashChanging(value)
				Me.SendPropertyChanging
				Me._PasswordHash = value
				Me.SendPropertyChanged("PasswordHash")
				Me.OnPasswordHashChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PasswordLastSetDate", DbType:="DateTime"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=7)>  _
	Public Property PasswordLastSetDate() As System.Nullable(Of Date)
		Get
			Return Me._PasswordLastSetDate
		End Get
		Set
			If (Me._PasswordLastSetDate.Equals(value) = false) Then
				Me.OnPasswordLastSetDateChanging(value)
				Me.SendPropertyChanging
				Me._PasswordLastSetDate = value
				Me.SendPropertyChanged("PasswordLastSetDate")
				Me.OnPasswordLastSetDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastSaltByteArray", DbType:="VarBinary(50)", UpdateCheck:=UpdateCheck.Never),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=8)>  _
	Public Property LastSaltByteArray() As System.Data.Linq.Binary
		Get
			Return Me._LastSaltByteArray
		End Get
		Set
			If (Object.Equals(Me._LastSaltByteArray, value) = false) Then
				Me.OnLastSaltByteArrayChanging(value)
				Me.SendPropertyChanging
				Me._LastSaltByteArray = value
				Me.SendPropertyChanged("LastSaltByteArray")
				Me.OnLastSaltByteArrayChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastSaltMechanismID", DbType:="Int"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=9)>  _
	Public Property LastSaltMechanismID() As System.Nullable(Of Integer)
		Get
			Return Me._LastSaltMechanismID
		End Get
		Set
			If (Me._LastSaltMechanismID.Equals(value) = false) Then
				Me.OnLastSaltMechanismIDChanging(value)
				Me.SendPropertyChanging
				Me._LastSaltMechanismID = value
				Me.SendPropertyChanged("LastSaltMechanismID")
				Me.OnLastSaltMechanismIDChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub Initialize()
		OnCreated
	End Sub
	
	<Global.System.Runtime.Serialization.OnDeserializingAttribute(),  _
	 Global.System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)>  _
	Public Sub OnDeserializing(ByVal context As StreamingContext)
		Me.Initialize
	End Sub
End Class

<Global.System.Runtime.Serialization.DataContractAttribute()>  _
Partial Public Class proc_GetGlobalMasterLoginDataByLoginNameResult
	
	Private _DatabaseName As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DatabaseName", DbType:="VarChar(50)"),  _
	 Global.System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
	Public Property DatabaseName() As String
		Get
			Return Me._DatabaseName
		End Get
		Set
			If (String.Equals(Me._DatabaseName, value) = false) Then
				Me._DatabaseName = value
			End If
		End Set
	End Property
End Class
